# Generated by Django 2.2.7 on 2019-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=80)),
                ('company_location', models.TextField()),
                ('comapny_Registration_number', models.IntegerField()),
            ],
            options={
                'unique_together': {('company_name',)},
            },
        ),
    ]
