# Generated by Django 2.2.7 on 2019-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfomodel',
            name='comapny_Registration_number',
            field=models.CharField(max_length=50),
        ),
    ]
