# Generated by Django 2.2.7 on 2019-11-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=70)),
                ('reviewer_company', models.CharField(max_length=50)),
                ('reviewer_subject', models.CharField(max_length=256)),
                ('reviewer_review', models.TextField()),
            ],
        ),
    ]
